server.port=8080

spring.application.name=tema1

spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234


spring.ai.google.genai.api-key=${GOOGLE_API_KEY}